"""Fair-price baseline cache.

Cache stores the deterministic baseline that `intelligence.evidence` computes:
range (low/mid/high), confidence, evidence-quality counters, and the per-source
evidence records. Narrative (explanation / red_flags / questions) is NEVER
cached — it's regenerated against the user's specific quoted price each time so
the wording reflects that specific overpayment amount.

On a cache hit, we use `FairRange`'s classmethod + `compute_verdict_math` so the
math is identical to the live path — no drift between cache and live verdicts.

TTL is 4h by default.
"""

import re

from app.intelligence.evidence import FairRange, compute_verdict_math
from app.services.redis import cache_get, cache_set

CACHE_TTL = 14400  # 4 hours

_CACHE_KEY_VERSION = "v3"  # bumped from v2 when baseline shape changed


def _build_key(classification: dict) -> str:
    """Normalized cache key for a SERVICE BASELINE (not a specific quote).

    Baselines are shared across users — the quoted_price is deliberately excluded.
    Locality goes in the key so users in different cities don't poison each
    other's baselines.
    """
    domain = classification.get("domain") or "unknown"
    service = classification.get("service") or "unknown"
    city = classification.get("city") or "global"
    country = classification.get("country") or "unknown"
    make = classification.get("make") or ""
    model = classification.get("model") or ""

    service_norm = re.sub(r"[^a-z0-9]+", "_", service.lower()).strip("_")
    city_norm = re.sub(r"[^a-z0-9]+", "_", city.lower()).strip("_")
    make_norm = re.sub(r"[^a-z0-9]+", "_", make.lower()).strip("_") if make else ""

    key = f"fc:{_CACHE_KEY_VERSION}:{domain}:{service_norm}:{city_norm}:{country}"
    if make_norm:
        key += f":{make_norm}"
    if model:
        model_norm = re.sub(r"[^a-z0-9]+", "_", model.lower()).strip("_")
        key += f":{model_norm}"

    return key


async def get_cached_baseline(classification: dict) -> dict | None:
    """Fetch cached baseline for this service+region, or None."""
    key = _build_key(classification)
    return await cache_get(key)


async def set_cached_baseline(classification: dict, baseline: dict) -> None:
    """Cache the deterministic baseline (4h TTL). Narrative is NOT cached."""
    key = _build_key(classification)
    await cache_set(key, baseline, ttl=CACHE_TTL)


def _baseline_to_fair_range(baseline: dict) -> FairRange:
    """Reconstruct a FairRange from a cached baseline dict.

    We store only what's needed to redo verdict math + render the sources panel.
    """
    return FairRange(
        fair_price_low=int(baseline.get("fair_price_low") or 0),
        fair_price_mid=int(
            baseline.get("fair_price_mid")
            or ((baseline.get("fair_price_low", 0) + baseline.get("fair_price_high", 0)) // 2)
        ),
        fair_price_high=int(baseline.get("fair_price_high") or 0),
        confidence_score=int(baseline.get("confidence_score") or 0),
        data_points_count=int(baseline.get("data_points_count") or 0),
        trusted_count=int(baseline.get("trusted_count") or 0),
        local_count=int(baseline.get("local_count") or 0),
        distinct_trusted_domains=int(baseline.get("distinct_trusted_domains") or 0),
        std_dev_cents=int(baseline.get("std_dev_cents") or 0),
        sources=list(baseline.get("sources") or []),
    )


def compute_verdict_from_baseline(baseline: dict, quoted_price: int | None) -> dict:
    """Recompute the verdict math against a cached baseline.

    Does NOT return explanation / red_flags / questions — those are generated by
    the LLM narrator in the orchestrator so they reflect the user's specific
    quote. A fallback narrative is left to the caller if narrative is skipped on
    the fast path.
    """
    fair_range = _baseline_to_fair_range(baseline)
    math = compute_verdict_math(fair_range, quoted_price)

    evidence = {
        "trusted_count": fair_range.trusted_count,
        "local_count": fair_range.local_count,
        "distinct_trusted_domains": fair_range.distinct_trusted_domains,
        "std_dev_cents": fair_range.std_dev_cents,
        "sources": fair_range.sources,
    }

    # Deterministic fallback narrative — orchestrator will overwrite if it
    # runs the narrator; but cached hits often skip it for speed.
    fair_low = fair_range.fair_price_low / 100
    fair_high = fair_range.fair_price_high / 100
    conservative = math.get("conservative_overpay", 0) / 100
    label = math.get("verdict", "fair")
    if quoted_price is None or quoted_price <= 0:
        explanation = (
            f"Cached fair market range: ${fair_low:,.0f}–${fair_high:,.0f}. "
            "Submit your quoted price for a personalized verdict."
        )
        red_flags = []
        questions = ["Provide your quoted price for a detailed analysis."]
    elif label == "fair":
        explanation = (
            f"Your quote falls within the fair market range of "
            f"${fair_low:,.0f}–${fair_high:,.0f}. This looks reasonable."
        )
        red_flags = []
        questions = [
            "Ask if the price includes parts and labor.",
            "Confirm warranty coverage on the work.",
        ]
    else:
        explanation = (
            f"Your quote is above the fair range of ${fair_low:,.0f}–${fair_high:,.0f}. "
            f"You may be overpaying by ${conservative:,.0f}."
        )
        red_flags = [
            f"Quote exceeds the fair ceiling of ${fair_high:,.0f} by ${conservative:,.0f}.",
        ]
        questions = [
            f"Ask why the price is ${conservative:,.0f} above the typical range of "
            f"${fair_low:,.0f}–${fair_high:,.0f}.",
            "Request an itemized breakdown of parts vs labor.",
        ]

    return {
        **math,
        "fair_price_low": fair_range.fair_price_low,
        "fair_price_mid": fair_range.fair_price_mid,
        "fair_price_high": fair_range.fair_price_high,
        "confidence_score": fair_range.confidence_score,
        "data_points_count": fair_range.data_points_count,
        "explanation": explanation,
        "red_flags": red_flags,
        "questions_to_ask": questions,
        "evidence": evidence,
    }
